### PR TITLE
Add a link to the CLA to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by rubyist**
Add a note in CONTRIBUTING about accepting the CLA.

:warning: This cannot be merged yet :warning:

@bkeepers is going to add an appropriate route to the CLA app, once that's done we can merge this.

### CODE REVIEW

**Comment by bkeepers** [comment]
:+1: anyone should now be able to accept the CLA by visiting: https://cla.github.com/github/git-lfs/accept

**Comment by rubyist** [comment]
:heart: you're the best @bkeepers

**Comment by zackse** [comment]
This link seems to have disappeared. Is accepting the CLA still required for new contributions?

**Comment by zackse** [comment]
Thanks, filed PR https://github.com/git-lfs/git-lfs/pull/2997 to address this in the contributor's guide.

**Pull request merged**
