### PR TITLE
Update nsis to repsect silent mode #789

### PR DESCRIPTION
**Pull request by lbarbisan-ullink**

### CODE REVIEW

**Comment by technoweenie** [comment]
Thanks! Now that I know that silent mode installs on windows are a thing, I'll make sure we keep the feature around if we move to something else like [InnoSetup](http://www.jrsoftware.org/isinfo.php).

**Comment by pascalberger** [comment]
@lbarbisan-ullink I tried to run `git-lfs-windows-amd64-1.1.0.exe` in silent mode using `/s` parameter, but it doesn't seem to make a difference (license & installation folder dialog are still shown). How is silent mode supposed to work

**Comment by lbarbisan-ullink** [comment]
`/S` in uppercase ?

**Comment by pascalberger** [comment]
Thanks! Uppercase is the key :+1:

**Comment by jed-frey** [comment]
If anyone finds this through Google (as I did) the command is now /SILENT & /VERYSILENT (I couldn't get /s or /S to work)

image

You can also do an install once and record the install settings and play them back:

image

**Comment by tolache** [comment]
Can it be installed on Windows Server Core?

**Comment by bk2204** [comment]
I don't know the answer to that, because it's not an environment we test.  You're welcome to try, though.

**Pull request merged**
