### PR TITLE
Fix Go 1.5 integration test issues

### PR DESCRIPTION
**Pull request by sinbad**
The test for lack of batch support turned it off globally on the test server then turned it back on, but since the server is shared between parallel tests, this introduces a race condition which can break other batch tests randomly. Instead, use a specific repo name to flag it.

Found this while investigating #625 although this isn't the complete fix. [Edit]Now it is.

### CODE REVIEW

**Comment by technoweenie** [comment]
:+1: I like the idea of encoding special behavior for tests. I was thinking about something like that for API responses with various objects too.

**Comment by sinbad** [comment]
I've added a second fix to this PR which resolves the remaining issue with batch tests in Go 1.5, there was a specific issue with expecting q.Wait() to return after all the transfer channel results had been received. Together these 2 seem to solve all the integration test issues in Go 1.5 in my tests.

**Comment by rubyist** [comment]
:+1:

**Comment by ttaylorr** [comment]
:+1:

**Pull request merged**
