### PR TITLE
Add icons to the Windows installer

### PR DESCRIPTION
**Pull request by sschuberth**
The icons were generated from the Git LFS web page's favicon file
available at https://git-lfs.github.com/favicon.png.

### CODE REVIEW

**Comment by ttaylorr** [comment]
@sschuberth -- these look great! 😍 

Have you thought about storing the .bmp and .ico files with LFS itself? We're not using LFS anywhere currently within this repo, but I think this could be a cool place to start. We could also look at extracting the Windows installer out to a separate repo if we don't want to store LFS objects within the github/git-lfs repo.

I'm going to give building this installer a shot on a Windows VM and report back once it's done 😄

**Comment by ttaylorr** [comment]
👋  again! I set up a Windows VM running 8.1, and built the installer using the Inno Setup Compiler (v5.5.9). Upon running the generated installer, I got an error message saying: "Bitmap image is not valid".

**Comment by sschuberth** [comment]
Very odd. I just tried again (on "real" Windows) and it works fine for me. However, I've converted the BMP from A8R8G8B8 to R5G6B5 to reduce its size. Mind trying again?

**Comment by sschuberth** [comment]
@ttaylorr To ensure the Windows installer is created correctly I've enabled AppVeyor CI builds via #1506 again. If you merge that PR first and enable AppVeyor CI for pull-requests, you should be able to download the installer artifact (similar to my build [here](https://ci.appveyor.com/api/buildjobs/1jrjk76rhjxbe20a/artifacts/git-lfs-windows-1.4.1.exe)) to check the installer before merging this PR.

**Comment by ttaylorr** [comment]
Thanks for updating this!

I cloned the new latest ref off of your `master` branch, but still encountered the same issue.

I'm going to take a look at the AppVeyor PR now and see if that's able to build this PR correctly. Sorry for all of the hassle, I'm (clearly) not a Windows developer 😄

**Comment by sschuberth** [comment]
I wonder if you're facing a line-ending conversion issue, that is, if your Git somehow treats the BMP as a text file ...

**Comment by ttaylorr** [comment]
> I wonder if you're facing a line-ending conversion issue

I'm using the latest build of Git Bash for Windows with the default settings applied. Just to be safe, I did a fresh clone of your repository and opened both images in Windows Photo Viewer, and they were viewed correctly.

@larsxschneider I know you have a few Windows machines. Can you give this one a shot if you get a chance?

**Comment by sschuberth** [comment]
> Have you thought about storing the .bmp and .ico files with LFS itself?

I just noticed I haven't answered that question yet: No, I did not think about that, but being so small files (the largest is 34 kb) I don't think they are a good case to show off the LFS feature.

**Comment by ttaylorr** [comment]
> I don't think they are a good case to show off the LFS feature.

I agree. I am revoking my previous suggestion! 😛

**Comment by ttaylorr** [comment]
Since I don't think I can retroactively build PRs with Appveyor, I'm going to merge this in 👍

**Comment by ttaylorr** [comment]
It works! 🎉 

screenshot 2016-09-06 13 19 11

**Comment by sschuberth** [comment]
Great! :-) Still wondering what went wrong when you tested in manually...

**Comment by ttaylorr** [comment]
Me too. Bah, Windows!

**Pull request merged**
