### PR TITLE
RPMs for Centos 5/6/7

### PR DESCRIPTION
**Pull request by andyneff**
A set of RPMs that will build git-lfs on CentOS 5, 6, and 7 for #328. A build_rpm.bsh script is included to basically automate installing (and build in the case of CentOS 5 and 6) the build dependencies, and build the git-lfs rpm and srpm

### CODE REVIEW

**Comment by technoweenie** [comment]
Instead of requiring ruby for people downloading rpms, is there a way that the rpm build script could generate them locally and have the rpm just bundle them?

Also, we're looking at changing how Go dependencies are managed (#330 or #331), which could change the project structure. It looks like the script calls `script/bootstrap` which means nothing should change. Just FYI.

**Comment by andyneff** [comment]
Ruby is NOT required for people downloading the rpm, it is only required to build the RPM from source (hence the BuildRequires:) It will never show up as a problem/dependency for someone downloading and using the final rpm. I only added ALLLLL the others for whomever chooses to build the RPMs for completeness.

It generates separate rpms for ruby/the gems/go ONLY for the purpose of building the final git-lfs. So in essence they are creating their own bundles (and installs them) just for the person creating the rpms (at release time... or for that enthusiastic user out there to DIY). This is best way to fit into how redhat does things.

If you do not like this, what I CAN look into is instead of installing the ruby/gem/go in the the system (prefix /) I can make the build script install them into the local prefix.

The person building the rpms also has the option of having thier own ruby/go setup, and just calling the rpmbuild command (really, the last line of the build_rpm script)  with --nodeps.

These are all things I want to cover in the README I have not written yet.

**Comment by technoweenie** [comment]
@andyneff: can you confirm this works with master? We've made some major changes (see #345).

**Comment by andyneff** [comment]
I will try and confirm tonight (and add an option to run off of currently checked out version instead of ONLY a tar ball)

**Comment by andyneff** [comment]
@technoweenie, with these new changes, everything works for building RPMs against the new master from yesterday, and I added running scripts/test to the rpm (to be run under the %check section)

**Pull request merged**
