### PR TITLE
Do not read the configuration from nonexistent file (remove redundant git call)

### PR DESCRIPTION
**Pull request by bozaro**

### CODE REVIEW

**Comment by michael-k** [comment]
I think this is better placed in `ListFromFile` itself.  Just return an empty string and `nil` if the file doesn't exist.

**Comment by bozaro** [comment]
@michael-k 
I move check to ```ListFromFile``` :)

**Comment by michael-k** [comment]
:+1:

**Comment by rubyist** [comment]
:+1: Thanks!

**Pull request merged**
