### PR TITLE
[wip] better tests for handling server failures

### PR DESCRIPTION
**Pull request by technoweenie**

### CODE REVIEW

**Comment by technoweenie** [comment]
This is an attempt to test various failure scenarios so we can catch things like #675 before they happen. Ideally, this PR fails until #675 is merged in, but I don't think that's quite the case just yet. But before I dig in, is this on the right track? Do the tests look useful?

I went with magic content strings because then it should be clear that the integration test is trying to trigger specific failure behavior on the server. The case statements are a lot more clear, despite the lines of copied code. If this approach works, we can replace `testingChunkedTransferEncoding()` with a magic string too.

**Comment by technoweenie** [comment]
While writing this, I expected all of the push tests with the batch api to pass, and the push tests with the legacy api to fail until #675 was merged. However, the batch api tests were failing too.

```
# STDOUT
    Tracking *.dat
    [master (root-commit) bdc7654] welp
     3 files changed, 7 insertions(+)
     create mode 100644 .gitattributes
     create mode 100644 bad.dat
     create mode 100644 good.dat
(1 of 2 files, 1 skipped) 2 B / 18 B, 16 B skipped                             
    push successful?

# STDERR
    + git lfs track '*.dat'
    + printf hi
    + printf status-batch-403
    + git add .gitattributes good.dat bad.dat
    + git commit -m welp
    + set +e
    + git push origin master
    To http://127.0.0.1:58006/test-push-failures-status-batch-403
     * [new branch]      master -> master
    + '[' 0 = 0 ']'
    + echo 'push successful?'
    + exit 1
```

Looks like the file was being skipped, but not treated as an error. 3671cc7f27130ecd468a04bc27c7554382d6f3fa changes the batch response handler too look for an object error before looking for a link relation.

**Comment by technoweenie** [comment]
So I merged #675 into this branch and pushed it up to a [temporary branch](https://github.com/github/git-lfs/compare/github:a62e510...github:b22949b) so CI can run. It passed!

https://travis-ci.org/github/git-lfs/builds/81463755

My plan now is:

1. Trigger #673 through a test in this PR
2. Ensure it passes when merged with #675.
3. Merge #675 
4. Merge #676

**Comment by rubyist** [comment]
:shipit:

**Comment by technoweenie** [comment]
Added a DNS test to this PR. Still passes in the temp merge branch:

https://github.com/github/git-lfs/compare/github:a62e510...github:f9b7779
https://travis-ci.org/github/git-lfs/builds/81469622

**Pull request merged**
