### PR TITLE
[WIP] Debian build vendor test excludes

### PR DESCRIPTION
**Pull request by javabrett**
Makes Debian build work on my machine, needs checks for correctness. #1290.

### CODE REVIEW

**Comment by ttaylorr** [comment]
Looks good! I think it may be useful to have some vendor tests run on these builds, since we use them in `script/test` on Travis. To remove the failing ones, you could try something similar to [what we have currently](https://github.com/github/git-lfs/blob/bf9bc1f29907cdf26cf29eb01df8baa9f17b45c2/script/test#L11-L13), which is basically just a combination of `go list` and a bunch of `grep -v`s.

**Comment by javabrett** [comment]
@ttaylorr You are right, and I had that initially in combination with `DH_GOLANG_INSTALL_ALL=1`.  Need to check the impact of that too, since a lot more files will be copied around and I don't know where they will end up, i.e. whether they pass through the build.

But I stopped when I hit the next package not on your list to fail, which was `github.com/spf13/cobra` - I should have added it, looks like it is the only remaining one to fail.

**Comment by ttaylorr** [comment]
Looks good to me. Thanks! 👍

**Comment by technoweenie** [comment]
LGTM :+1: 

I think a note should be added to `script/test` so we know to keep both excluded packages in sync.

**Pull request merged**
