### PR TITLE
Make sure some git commands statuses are waited

### LINKED ISSUE #1562: Cannot push repository with many files: resource temporarily unavailable
I just converted a repository using BFG to track many PDF files (around 78,000). When I try to push, all the data gets to the server, but it eventually fails:

```
$ git push
Warning: remote port forwarding failed for listen port 2224
Git LFS: (0 of 68335 files, 200 skipped) 0 B / 15.66 GB, 70.54 MB skipped                                                                                                    
Git LFS: (0 of 68235 files, 300 skipped) 0 B / 15.64 GB, 98.60 MB skipped                                                                                                    
Git LFS: (0 of 0 files, 4848 skipped) 0 B / 0 B, 1.38 GB skipped                                                                                                             packet_write_wait: Connection to 10.20.90.232 port 7999: Broken pipe


Git LFS: (0 of 0 files, 97 skipped) 0 B / 0 B, 7.20 MB skipped                                                                                                               Error scanning for Git LFS files

Errors logged to /Users/andy/Projects/natera/eng/lims/lfs/objects/logs/20161006T161227.640338372.log
Use `git lfs logs last` to view the log.
error: failed to push some refs to 'ssh://git@stash.myorg.com:7999/eng/prodlims.git'
```

And `/Users/andy/Projects/myorg/eng/lims/lfs/objects/logs/20161006T161227.640338372.log` contains:

```
git-lfs/1.4.1 (GitHub; darwin amd64; go 1.7.1)
git version 2.10.0

$ git-lfs pre-push origin ssh://git@bitbucket.myorg.com:7999/eng/prodlims.git
Error scanning for Git LFS files

fork/exec /usr/local/Cellar/git/2.10.0/libexec/git-core/git: resource temporarily unavailable

ENV:
LocalWorkingDir=
LocalGitDir=/Users/andy/Projects/myorg/eng/lims
LocalGitStorageDir=/Users/andy/Projects/myorg/eng/lims
LocalMediaDir=/Users/andy/Projects/myorg/eng/lims/lfs/objects
LocalReferenceDir=
TempDir=/Users/andy/Projects/myorg/eng/lims/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.
__GIT_PROMPT_DIR=/Users/andy/.zsh-git-prompt
GIT_IMPLICIT_WORK_TREE=0
GIT_PREFIX=
GIT_PROMPT_EXECUTABLE=python
```

Near the end of the command running (which takes about an hour to error out) I noticed around 600+ git processes running.

I am thinking that it might be hitting some ulimit. I tried increasing my `file decriptor` and `process` limits (I can't seem to go higher than 2048 processes):

```
$ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2048
-n: file descriptors                262144
```

But it didn't seem to help. Is it possible I am still running into 2048 process limit? If so, what can I do to get this repository pushed?

```
$ git --version
git version 2.10.0
$ git lfs version
git-lfs/1.4.1 (GitHub; darwin amd64; go 1.7.1)              
$ sw_vers -productVersion 
10.12
```

### PR DESCRIPTION
**Pull request by jjgod**
Fix #1562.

### CODE REVIEW

**Comment by ttaylorr** [comment]
Hi @jjgod, thanks very much for sending this in. I'm interested to hear a little bit more about why `defer`-ing a call to `*cmd.Wait()` fixes this issue. At first blush, my thinking is that this halts the delays of functions that spawn commands, until those commands have exited; but I'd love to hear more from your side on this.

**Comment by jjgod** [comment]
Please see the discussion at #1562, basically there were a lot of git zombie processes created by the scanner. The fix I made is not simply deferring the Wait() call, but rather ensuring the Wait() is called at least once for those commands, because it wasn't before the fix. I believe that was an oversight. If you compare that with other functions that launches git in the same file, you will notice that they all wait for the exit status, otherwise the child process will stay as zombie until the parent process exits, this is a typical Unix programming mistake.

**Comment by jjgod** [comment]
Introduced by #1051

**Comment by technoweenie** [comment]
Dang, you rock :metal: I actually ran across these functions yesterday while looking at the scanner for a major rewrite of it. I made a mental note to check them out later in relation to this issue, but you beat me to it :)

Thanks for taking a look!

**Comment by technoweenie** [comment]
Hey, can you sign this CLA? Our webhook is having some issues, but you should be able to sign it at https://cla.github.com/github/git-lfs/accept.

**Comment by jjgod** [comment]
Sorry, but I will not be able to sign the CLA in a short term at least due to the contribution is done during work time with a work facility, it has to be checked by my employer first.

Would it be possible for you guys to make a similar fix in essence of this instead? Or simply rewrite that part of the code so the fix can be no longer required. Either way we can proceed without waiting for me to sign the CLA.

**Comment by technoweenie** [comment]
No worries! I posted https://github.com/github/git-lfs/pull/1656, which will make it into the next release (v1.5.0), _hopefully_ this week.

Thanks so much for your help :)

**Pull request closed without merging**
