### PR TITLE
Add code of conduct to contributing guidelines

### PR DESCRIPTION
**Pull request by bkeepers**
We are intending to adopt the soon-to-be-announced [Open Code of Conduct](http://todogroup.org/opencodeofconduct) for all @github projects. This adds it to the contributing guidelines. Let me know if you have any questions or concerns.

### CODE REVIEW

**Comment by rubyist** [comment]
Looks like they miss some url parsing on their side. Should we file an issue? Using a space in the URL also fixes it.

open_code_of_conduct

**Comment by rubyist** [comment]
Since this links to text on a third party site rather than incorporates the text into the repo I'm wondering if there's any mechanism in place to notify maintainers of any changes to the CoC text?

**Comment by bkeepers** [comment]
I opened https://github.com/todogroup/opencodeofconduct/issues/15 to report the issue.

**Comment by technoweenie** [comment]
The Code of Conduct looks good to me. However, like @rubyist, I am a bit concerned about the technical implementation of this. The todo group site is also just http, leaving a tiny chance that man in the middle attack could drastically change the contents without our knowledge.

I'd like a model where I could register to have a bot send pull requests for a `./CODE-OF-CONDUCT.md` file or something. Then the content is hosted inside the repository, and changes are clearly visible to contributors.

I'm :+1: to merge this right now though and get the ball rolling.

**Comment by rubyist** [comment]
Agree with all of that :+1: on a merge

**Comment by bkeepers** [comment]
That's all really great feedback.

> The todo group site is also just http, leaving a tiny chance that man in the middle attack could drastically change the contents without our knowledge.

It is currently a Pages site, so it would need to be moved somewhere else since pages doesn't support https.

> I'd like a model where I could register to have a bot send pull requests for a ./CODE-OF-CONDUCT.md file or something. Then the content is hosted inside the repository, and changes are clearly visible to contributors.

That came up as an option at some point. I'm not opposed.

The thinking for the current approach is that, unlike a license, which applies to the code no matter where it exists, the code of conduct applies to online interactions.

Most [other people that are adopting the code of conduct](https://github.com/todogroup/opencodeofconduct#what-companies-support-or-use-the-open-code-of-conducts) do it by posting the text on their own website. We could certainly do that as well.

**Comment by technoweenie** [comment]
Ah, Pages. I hope we can support SSL there one day :)

> The thinking for the current approach is that, unlike a license, which applies to the code no matter where it exists, the code of conduct applies to online interactions.

That's legit. Until people start being jerks in commit messages :trollface: Anyways, I'm happy with this PR for now.

**Pull request merged**
