### PR TITLE
Update LFS license file to reflect MIT license use

### PR DESCRIPTION
**Pull request by hoolio**
Adding language at the top of the file that makes clear that the project is licensed under the MIT license, with a link to the Wikipedia article explaining what that license is. 

Users should have an easy way to determine what standard OSS license applies to a project, if any, by quickly looking at it.

### CODE REVIEW

**Comment by technoweenie** [comment]
Can you make this a plaintext change?

> This project is licensed under the MIT license:
> 
>   https://en.wikipedia.org/wiki/MIT_License

The license isn't a markdown file, and this change keeps the file readable from a terminal. Or you could just rename the file to `license.md` :)

**Comment by hoolio** [comment]
@technoweenie - yep, will do

**Comment by technoweenie** [comment]
Thanks!

**Comment by alamry111** [comment]
[LICENSE.txt](https://github.com/user-attachments/files/22947509/LICENSE.txt)

**Pull request merged**
