### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ro31337**
Add installation instructions for Windows users.

### CODE REVIEW

**Comment by technoweenie** [comment]
@ro31337 Thanks, I've never use chocolatey. Is there any documentation on how that works? I'd hate to inadvertently break it in a future release.

**Comment by technoweenie** [comment]
Also, please sign the CLA so I can merge this :)

**Comment by ro31337** [comment]
It says "You accepted this agreement for github/git-lfs on December 16, 2015."

Chocolatey is wide-spread, 34M downloads. Here is the main website: https://chocolatey.org/

@technoweenie let me know if you can't merge this, we can delete this pull request and I'll open new one.

**Comment by technoweenie** [comment]
Ah, had issues with the CLA app updating the status. Thanks!

**Pull request merged**
