### PR TITLE
Fsck command

### LINKED ISSUE #262: git-lfs fsck (bitrot detection)
Would anyone else find it useful if git-lfs offered a fsck command that verified the integrity of tracked (large) files?  Re-calculating hashes for files under .git/lfs/objects and comparing against the object name (dir+filename) could serve as an integrity check.

My goal with this would be to detect bitrot in large files like photos and mp3s.

### PR DESCRIPTION
**Pull request by michael-k**
This PR is built on #280 by @zeroshirts and #290 by @technoweenie.

I transferred the test to the new test environment. Should be enough to close #262.

@zeroshirts:
I squashed a05e331 (*Add LFS fsck command*) and 1c8c54d (*code review changes*) together and moved  `file.Close()` right after `_, err = io.Copy(oidHash, f)`.¹  I hope this is ok with you!?

¹ See comment in 2f6c3be.  If `io.Copy` fails, we still want to close the file.

### CODE REVIEW

**Comment by michael-k** [comment]
Some comments on questions raised in #290:

**Is `fsck` the right name?**

Consistent with `git` and `git-annex`. → Yes

**Is deleting the corrupt objects the right default?**

Potential data loss. → No

>  I'm not sure what we could do to fix files.

Not git-lfs' job.

**Observations (not necessarily blockers for this PR)**

Nice things we should document somewhere in order to do them in other PRs.  I'd say the current user interface is a good default.

**Comment by zeroshirts** [comment]
LGTM

**Comment by technoweenie** [comment]
Awesome, thanks for picking this back up. I'd like to ship this with Git LFS v0.5.2 some time next week.  

We do need to add a [man page](https://github.com/github/git-lfs/tree/master/docs/man) for this.

**Comment by michael-k** [comment]
:+1: I've put the man page on my todo list for the next days.

**Comment by technoweenie** [comment]
> sha256sum: command not found

I use `shasum -a 256`, but it may be easier to write one in Go. I have no idea what we can use that will work cross platform.

**Comment by technoweenie** [comment]
Here's one idea: https://gist3.github.com/technoweenie/85e1611dff2289bd7e18

**Comment by michael-k** [comment]
The gist3 link returns a 404. This one works, though: https://gist.github.com/technoweenie/85e1611dff2289bd7e18

I changed `sha256sum` to `shasum -a 256`. Other tests are using `shasum -a 256` too, therefore I thing it's out of scope for this PR to move to a custom hash program.

**Comment by michael-k** [comment]
I added a man page. From my POV this PR is ready.

**Comment by technoweenie** [comment]
> Other tests are using shasum -a 256 too, therefore I thing it's out of scope for this PR to move to a custom hash program.

Ideally all shell scripts in git-lfs are written for lowest common denominator sh environments. I have no idea what the standard shasum command is, or if there even is one. I agree that it's not worth adding a custom command until we need to though.

**Pull request merged**
