### PR TITLE
Added Linux Mint distro to packagecloud push, issue #1074.

### PR DESCRIPTION
**Pull request by javabrett**
I haven't got my deb build running yet to be able to test this via push to my packagecloud.  Can build OK but the dpkg build complains about imports.

So I'm not sure this is correct, but someone with a working build would be able to test it, perhaps for the next release.

### CODE REVIEW

**Comment by technoweenie** [comment]
@javabrett Thanks for submitting! Can you post the import issues that dpkg complains about?

**Comment by javabrett** [comment]
My problem may be that I am on downstream x2 LinuxMint 17.1 Rebecca, which is based on Ubuntu 14.04 Trusty, which is Debian Jessie.  I don't use Go to fetch my git-lfs clone - I do set GOPATH and have the source correctly placed in there.

I now suspect that my real problem is the lack of a properly-installed `golang-go` dpkg package.  I did have the seemingly best available binary package from the Ubuntu universe installed, but it was really old, 2:1.2.1-2ubuntu1, and you can't build git-lfs with that.  So I build and installed a current Go 1.6, set `PATH`, which is fine to build git-lfs, but when running the dpkg build it will reference the installed package.

```
cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"
```

```
which go && go version
/usr/local/go/bin/go
go version go1.6 linux/amd64
```

```
cd $GOPATH/src/github.com/github/git-lfs
script/bootstrap && bin/git-lfs version
Using go1.6
git-lfs/1.1.1 (GitHub; linux amd64; go 1.6; git 8f90f59)
```

The dpkg build fails so:

```
dpkg-buildpackage -us -uc
dpkg-buildpackage: source package git-lfs
dpkg-buildpackage: source version 1.1.1
dpkg-buildpackage: source distribution stable
dpkg-buildpackage: source changed by Stephen Gelman <gelman@getbraintree.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build git-lfs
 fakeroot debian/rules clean
dh clean --buildsystem=golang --with=golang
   dh_testdir -O--buildsystem=golang
   dh_auto_clean -O--buildsystem=golang
   debian/rules override_dh_clean
make[1]: Entering directory `/home/<redacted>/go/src/github.com/github/git-lfs'
rm -f debian/debhelper.log
rm -rf man
dh_clean
make[1]: Leaving directory `/home/<redacted>/go/src/github.com/github/git-lfs'
 dpkg-source -b git-lfs
dpkg-source: info: using source format `3.0 (native)'
dpkg-source: info: building git-lfs in git-lfs_1.1.1.tar.gz
dpkg-source: info: building git-lfs in git-lfs_1.1.1.dsc
 debian/rules build
dh build --buildsystem=golang --with=golang
   dh_testdir -O--buildsystem=golang
   dh_auto_configure -O--buildsystem=golang
   debian/rules override_dh_auto_build
make[1]: Entering directory `/home/<redacted>/go/src/github.com/github/git-lfs'
dh_auto_build
package github.com/github/git-lfs
	imports github.com/github/git-lfs/commands
	imports github.com/github/git-lfs/lfs
	imports github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm: must be imported as _nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm
package github.com/github/git-lfs
	imports github.com/github/git-lfs/commands
	imports github.com/github/git-lfs/lfs
	imports github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm
	imports github.com/github/git-lfs/vendor/_nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm/md4: must be imported as _nuts/github.com/ThomsonReutersEikon/go-ntlm/ntlm/md4
----- >-8 ----- >-8 ----- >-8 ----- >-8 -----
package github.com/github/git-lfs
	imports github.com/github/git-lfs/commands
	imports github.com/github/git-lfs/git
	imports github.com/github/git-lfs/subprocess
	imports github.com/github/git-lfs/vendor/_nuts/github.com/rubyist/tracerx: must be imported as _nuts/github.com/rubyist/tracerx
package github.com/github/git-lfs/test/git-lfs-test-server-api
	imports github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra: must be imported as _nuts/github.com/spf13/cobra
dh_auto_build: go install -v github.com/github/git-lfs/... returned exit code 1
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory `/home/<redacted>/go/src/github.com/github/git-lfs'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

If I remove the old `golang-go` package, it proves that this old version is referenced in the dpkg build, which is probably not good:

```
$ dpkg-buildpackage -us -uc
dpkg-buildpackage: source package git-lfs
dpkg-buildpackage: source version 1.1.1
dpkg-buildpackage: source distribution stable
dpkg-buildpackage: source changed by Stephen Gelman <gelman@getbraintree.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build git-lfs
dpkg-checkbuilddeps: Unmet build dependencies: golang-go:native (>= 1.3.0)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
```

I did not find reliable sources for deb-packaged current versions of Go 1.5/1.6 binaries.  My source build didn't seem to install via the deb package route, so I think this leaves me short for a local deb build of git-lfs.

**Comment by javabrett** [comment]
Hmmm, there are still some things I don't understand about how the packages are being built and uploaded to packagecloud.  Also of possible note: in packagecloud for 1.1.1, all the ubuntu packages are present, but in 1.1.2 they are gone.  That may be intentional, or maybe there was a different release person or limited machines.

I get the feeling that my package files are not in the right location or with the right names or something.  `dpkg-buildpackage` ended with `dpkg-deb: building package `git-lfs' in `../git-lfs_1.1.1_amd64.deb'.` ... so one level up from my git-lfs working-copy.  `packagecloud.rb` on the other hand is looking for `repos/**/*.deb` etc., so it feels like there is some other processing/shuffling being done.  Is that noted anywhere?

I found that packagecloud is rejecting duplicate filenames.  It seems OK with them under different paths, since 1.1.2 has that.  I would imagine that equivalent upstream distros could often use an identical package.

**Comment by javabrett** [comment]
Hmmm, there are still some things I don't understand about how the packages are being built and uploaded to packagecloud.  Also of possible note: in packagecloud for 1.1.1, all the ubuntu packages are present, but in 1.1.2 they are gone.  That may be intentional, or maybe there was a different release person or limited machines.

I get the feeling that my package files are not in the right location or with the right names or something.  `dpkg-buildpackage` ended with `dpkg-deb: building package `git-lfs' in `../git-lfs_1.1.1_amd64.deb'.` ... so one level up from my git-lfs working-copy.  `packagecloud.rb` on the other hand is looking for `repos/**/*.deb` etc., so it feels like there is some other processing/shuffling being done.  Is that noted anywhere?

I found that packagecloud is rejecting duplicate filenames.  It seems OK with them under different paths, since 1.1.2 has that.  I would imagine that equivalent upstream distros could often use an identical package.

**Comment by javabrett** [comment]
#1102 and #1103 finally make this testable.  I suspect there have been some recent gremlins in packagecloud upload, hopefully those sort them out.  The results can be viewed at https://packagecloud.io/brettrandall/git-lfs (which I will later delete, test only).

**Comment by javabrett** [comment]
See also https://github.com/computology/packagecloud-ruby/issues/14 .

**Comment by technoweenie** [comment]
Hey, sorry for not pinging the best person to help you (paging @andyneff), and then heading out of town for a couple weeks (I was at GDC when I replied). Thanks for posting details, and filing the package cloud issue and the various other LFS PRs :metal:

It looks like you solved the mystery yourself:

* Lack of the vendor env var failed the builds with go 1.6.
* Improper packagecloud gem usage lead to duplicate packages not being uploaded.

Did I miss anything?

> should there be another issue to make that behaviour (go vender installs) the default on Go 1.6?

I'm a big fan of the new go vendor stuff. I'll add updating it to the roadmap.

**Comment by javabrett** [comment]
This should be good to go now.  Here's my test-run:

```
$ ruby script/packagecloud.rb 
pushing repos/debian/8/git-lfs_1.1.1_amd64.deb to "debian/jessie"
pushing repos/debian/8/git-lfs_1.1.1_amd64.deb to "linuxmint/rebecca"
pushing repos/debian/8/git-lfs_1.1.1_amd64.deb to "linuxmint/rafaela"
pushing repos/debian/8/git-lfs_1.1.1_amd64.deb to "linuxmint/rosa"
pushing repos/debian/8/git-lfs_1.1.1_amd64.deb to "ubuntu/trusty"
pushing repos/debian/8/git-lfs_1.1.1_amd64.deb to "ubuntu/vivid"
pushing repos/debian/8/git-lfs_1.1.1_amd64.deb to "ubuntu/wily"
[Debian 8](https://packagecloud.io/brettrandall/git-lfs/packages/debian/jessie/git-lfs_1.1.1_amd64.deb/download)
```

Results viewable at https://packagecloud.io/brettrandall/git-lfs .

I'm rebasing this to current master, and sneaking-in one additional nitpick commit about a hardcoded-name that we have a variable for in the final status message/test-link.

**Comment by technoweenie** [comment]
Awesome, thanks. About to put this to good use :)

**Pull request merged**
