### PR TITLE
Command var scope

### PR DESCRIPTION
**Pull request by technoweenie**
I thought changing `lfs.Environ()` to accept a `*config.Configuration` and `*transfer.Manifest` (instead of using global values) would be easy.  However, I wanted a spot for various "global" config objects to be created for all commands, so I picked `commands.Run()`. I may look for a way to pass some kind of context to each command and remove those too.

I built this PR off #1430, so view this diff instead: [transfer-manifest...command-var-scope](https://github.com/github/git-lfs/compare/transfer-manifest...command-var-scope)

### CODE REVIEW

**Comment by ttaylorr** [comment]
Looks good, I like this isolation. Curious why we need to give a `func() *cobra.Command` as an argument to `RegisterSubcommand`. It would be cool to only have to create commands as needed, but it looks like they all get created anyway.

**Comment by technoweenie** [comment]
Returning a function lets us initialize the cobra commands whenever we want (as in, after all the config objects are initialized). Also, the lock commands currently return nil if they're not enabled. Obviously that won't always be the case, but I think we can keep `isCommandEnabled()` around for other future commands.

**Comment by ttaylorr** [comment]
Ah, delaying until we have the config loaded is pretty sweet. Works for me 👍

**Comment by ttaylorr** [comment]
Pending a succesful build: 🚢

**Pull request merged**
