### PR TITLE
Prevent to track file outside git repository

### PR DESCRIPTION
**Pull request by Aorjoa**
according #293 my report issue, now i already hack code for fixed.
if anybody run `$ git lfs track` outside git repository it's show message "Git LFS cannot perform outside git repository."

### CODE REVIEW

**Comment by rubyist** [comment]
Thanks for the PR! One piece of feedback I have is, we have some existing code that determines the local git directory and sets `lfs.LocalGitDir` on init. We should be able to just check whether or not that it set and avoid execing a git command here. :+1: for the test, that looks legit.

/cc https://github.com/github/git-lfs/issues/200

**Comment by Aorjoa** [comment]
:+1:

**Comment by Aorjoa** [comment]
I was change code for check lfs.LocalGitDir == ""

**Comment by michael-k** [comment]
I think it's better to inline the function `workingInsideGit()` like this:
```go
if lfs.LocalGitDir == "" {
	Print("Git LFS cannot perform outside git repository.")
	return
}
```

Small helper functions are considered good style in go, but in this case it's just a bunch of negations (equal → false → negation) which makes it harder to understand what happens on a low level (maintainability).

The message in `Print()` makes it clear what happens on a high level (readability), so imho the “speaking name” `workingInsideGit` adds no further benefit.

And last, but not least, I'm voting in favor of squashing the commits together. :)

**Comment by Aorjoa** [comment]
Thank you very much for your advice. :+1: I would like to change the message to "Not in a Git LFS repository". Do you think it's clear enough? @michael-k  :)

**Comment by michael-k** [comment]
git itself says:
```
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
or with `GIT_DISCOVERY_ACROSS_FILESYSTEM=1`:
```
fatal: Not a git repository (or any of the parent directories): .git
```
`Not in a Git LFS repository` might not be correct, as `lfs.LocalGitDir` does not check if git-lfs was initialized.

**Comment by technoweenie** [comment]
I redid this PR as #323.  Normally I wouldn't do something like that, but I wanted to test this on the new test suite.  The actual command change is pretty minimal.  My PR takes @michael-k's suggestion into account.  It also doesn't change the import formatting in `commands/command_track.go`.

**Pull request closed without merging**
