### PR TITLE
teach script/integration.go about GIT_LFS_TEST_MAXPROCS

### PR DESCRIPTION
**Pull request by technoweenie**
Found an intermittent test issue running `script/cibuild` on mac. While investigating, I noticed that `GIT_LFS_TEST_MAXPROCS` isn't even used now. The intermittent issue goes away when `GIT_LFS_TEST_MAXPROCS=1` too.

### CODE REVIEW

**Comment by ttaylorr** [comment]
👍 , going to keep looking for the cause of this failure in parallel.

**Comment by technoweenie** [comment]
Kept digging, and eventually figured this out. I added random per-request IDs in the test server, so I could see all the log messages for single requests. The intermittent test failures were all basic auth errors, where the client sent `path:test-credentials` to the server. This is only used [here](https://github.com/github/git-lfs/blob/3a3f0e14f5e71cec018270bf919eb6c17a710e34/test/test-credentials.sh#L69), in `test-credentials.sh`.  

So, the client is sending the wrong credentials in files like `test-fetch.sh`, `test-clone.sh`, and `test-happy-path.sh`. Why is that?

Here's a `GIT_TRACE` log of a request:

```
   14:53:18.712775 git.c:344               trace: built-in: git 'credential' 'fill'
   14:53:18.713366 run-command.c:334       trace: run_command: 'git credential-osxkeychain get'
   14:53:18.713855 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git credential-osxkeychain get' 'git credential-osxkeychain get'
   14:53:18.717604 git.c:561               trace: exec: 'git-credential-osxkeychain' 'get'
   14:53:18.718084 run-command.c:334       trace: run_command: 'git-credential-osxkeychain' 'get'
   trace git-lfs: Filled credentials for http://127.0.0.1:54271/test-fetch
   trace git-lfs: HTTP: POST http://127.0.0.1:54271/test-fetch.git/info/lfs/objects/batch
   trace git-lfs: HTTP: 200
   14:53:18.790117 git.c:344               trace: built-in: git 'credential' 'approve'
   14:53:18.790657 run-command.c:334       trace: run_command: 'git credential-osxkeychain store'
   14:53:18.791086 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git credential-osxkeychain store' 'git credential-osxkeychain store'
   14:53:18.795729 git.c:561               trace: exec: 'git-credential-osxkeychain' 'store'
   14:53:18.796475 run-command.c:334       trace: run_command: 'git-credential-osxkeychain' 'store'
   14:53:18.824842 run-command.c:334       trace: run_command: 'git credential-osxkeychain store'
   14:53:18.825392 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git credential-osxkeychain store' 'git credential-osxkeychain store'
   14:53:18.829337 git.c:561               trace: exec: 'git-credential-osxkeychain' 'store'
   14:53:18.829904 run-command.c:334       trace: run_command: 'git-credential-osxkeychain' 'store'
   14:53:18.857622 run-command.c:334       trace: run_command: 'git credential-lfstest store'
   14:53:18.858097 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git credential-lfstest store' 'git credential-lfstest store'
   14:53:18.862656 git.c:561               trace: exec: 'git-credential-lfstest' 'store'
   14:53:18.863061 run-command.c:334       trace: run_command: 'git-credential-lfstest' 'store'
   14:53:18.868086 run-command.c:334       trace: run_command: 'git credential-lfstest store'
   14:53:18.868534 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git credential-lfstest store' 'git credential-lfstest store'
   14:53:18.872848 git.c:561               trace: exec: 'git-credential-lfstest' 'store'
   14:53:18.873362 run-command.c:334       trace: run_command: 'git-credential-lfstest' 'store'
```

First, the client calls `git credential fill`, which returns early from the `osxkeychain` only. After the successful request, `git credential approve` calls the `store` command on both the `osxkeychain` and `lfstest` stores.  So my hunch: `test-credentials.sh` saved `path:test-credentials` to both credential helpers, and the failing tests fetched the same credentials.

This fixes it by enabling `credential.usehttppath`, so that all of the credentials are unique per test repository.

**Comment by technoweenie** [comment]
It seems only the osx build with travis' default git version (1.8.x) is failing now, due to a timeout when running `test/test-credentials.sh`. My guess is that it's waiting on user/password input for something. Now it's setting `GIT_TERMINAL_PROMPT=0` so git won't prompt in the test anymore. This means the faulty test will be skipped in environments with travis' default git version. **All** of the osx builds should be good to go now... :metal:

**Comment by ttaylorr** [comment]
Nice 👍

**Pull request merged**
