### PR TITLE
Support chunked Transfer-Encoding

### PR DESCRIPTION
**Pull request by ryansimmen**
Fixes github/git-lfs#385

### CODE REVIEW

**Comment by technoweenie** [comment]
Easy peasy! This needs a test.

**Comment by technoweenie** [comment]
I'd like to see a test that uses the [git and git lfs server that shell integration tests use](https://github.com/github/git-lfs/blob/master/test/cmd/lfstest-gitserver.go). I think we can do this by sending a `Transfer-Encoding` header in the [post](https://github.com/github/git-lfs/blame/968faba7e11786e3884dba1e797f816f2c216541/test/cmd/lfstest-gitserver.go#L131) and [batch](https://github.com/github/git-lfs/blame/968faba7e11786e3884dba1e797f816f2c216541/test/cmd/lfstest-gitserver.go#L207) endpoints if the integration test's repo name has "chunked-transfer-encoding" in the name.

**Comment by ryansimmen** [comment]
I've updated the PR with a few small integration tests.

**Comment by rubyist** [comment]
code and tests look :+1:

**Pull request merged**
