### PR TITLE
Create git-lfs.bash_completion.sh for basic completion support

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Refer to hub's completion (https://github.com/github/hub/blob/master/etc/hub.bash_completion.sh)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
This is not a perfect completion, but it'll help, I'll finish it when I have time :)

**Comment by bkeepers** [comment]
Hey @PeterDaveHello, it looks like this is still in progress. Do you think you'll finish it soon, or do you want to close this for now?

**Comment by technoweenie** [comment]
Hey @PeterDaveHello, haven't seen you in a while :)  I'm closing this because we're adding a new `git lfs integrate` command in https://github.com/github/git-lfs/pull/1133. The idea is that `integrate` can support zsh, bash, and other autocompletions. There's even the possibility we can grow beyond just autocompletion, depending on user needs. The really nice thing though is zsh autocomplete code is generated from the go package, reducing duplication, and making it easy for users to update with each new release.

Let me know if you (or anyone else that's reading this) wants to help add bash autocompletion to the upcoming `git lfs integrate` command.

**Comment by PeterDaveHello** [comment]
Oops, sorry that I didn't notice this, that's fine, I may not have enough time to work on the new command, but I'll try it once it's finished :smile:

**Pull request closed without merging**
