### PR TITLE
I think this should be "Once installed" and not "One installed", but …

### PR DESCRIPTION
**Pull request by GabLeRoux**
…close this if I'm wrong ;)

### CODE REVIEW

**Comment by ttaylorr** [comment]
👋  thanks for this! Once you sign the CLA, we will be good to merge 😄

**Comment by fnkr** [comment]
...and "run" should be changed to "done", right?

> This only needs to be **run** once per machine.

to

> This only needs to be **done** once per machine.

**Comment by ttaylorr** [comment]
@GabLeRoux if you're still interested in working this, signing the CLA and updating according to @fnkr's comment would be enough for me to merge 👍

**Comment by ttaylorr** [comment]
Hey @GabLeRoux, this looks great! If you merge the latest upstream changes from `master` into this branch, we can definitely go ahead and merge 👍

**Comment by ttaylorr** [comment]
Thanks again!

**Pull request merged**
