### PR TITLE
Explain a subtlety of client handling for "download" batch action

### PR DESCRIPTION
**Pull request by epriestley**
This may not be worth pulling or the best method or place to express the idea, but the behavior wasn't self-evident to me from the documentation while implementing an LFS server, even though it makes sense now that I understand the interaction.

### CODE REVIEW

**Comment by technoweenie** [comment]
Looks good to me :+1:

**Comment by sinbad** [comment]
Hmm, I'm not sure this is correct, it implies that the server *must* respond with a download link when the operation is `upload` in order for the upload to be skipped, when in fact simply *omitting* the upload link in the response does that. You don't have to provide a download link instead and doing so makes no difference vs omitting - git-lfs just doesn't find a link of type `upload` in both cases. I don't think we should be telling server implementors that they have to provide a download link in upload requests.

**Comment by epriestley** [comment]
Ah, I must have misunderstood the `prePushCheckForMissingObjects()` / `NewDownloadCheckQueue()` interaction -- and, in retrospect, my test case would have worked for either behavior. I'll fix this.

**Comment by epriestley** [comment]
#1087 reverts this and properly attributes the behavior to the `upload` action instead. Sorry about that!

**Comment by sinbad** [comment]
Thanks for the fast turnaround!

**Pull request merged**
