### PR TITLE
Add xenial repo

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by technoweenie** [comment]
Have you confirmed [the debian 8 package](https://packagecloud.io/github/git-lfs/packages/debian/jessie/git-lfs_1.2.0_amd64.deb/download) works on Ubuntu xenial?

**Comment by graingert** [comment]
```
 sudo gdebi git-lfs_1.2.0_amd64.deb  
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

Git Large File Support
 An open source Git extension for versioning large files
Do you want to install the software package? [y/N]:y
Selecting previously unselected package git-lfs.
(Reading database ... 502457 files and directories currently installed.)
Preparing to unpack git-lfs_1.2.0_amd64.deb ...
Unpacking git-lfs (1.2.0) ...
Setting up git-lfs (1.2.0) ...
Processing triggers for man-db (2.7.5-1) ...
 graingert@kvell  ~/Downloads  git lfs install
Git LFS initialized.
```

**Comment by technoweenie** [comment]
Great, thanks! I should be able to push v1.2 to packagecloud, as well.

**Comment by technoweenie** [comment]
```
$ package_cloud push github/git-lfs/ubuntu/xenial git-lfs_1.2.0_amd64.deb
Using https://packagecloud.io with token:******df8d
Looking for repository at github/git-lfs... success!
Pushing git-lfs_1.2.0_amd64.deb... success!

$ package_cloud push github/git-lfs/ubuntu/xenial git-lfs_1.2.0_i386.deb
Using https://packagecloud.io with token:******df8d
Looking for repository at github/git-lfs... success!
Pushing git-lfs_1.2.0_i386.deb... success!
```

If you happen to have [our packagecloud repo installed](https://packagecloud.io/github/git-lfs/install), you should be able to install LFS v1.2 with `apt-get` now.

**Pull request merged**
