### PR TITLE
add instructions to install from MacPorts

### PR DESCRIPTION
**Pull request by skymoo**

### CODE REVIEW

**Comment by technoweenie** [comment]
Hey @skymoo thanks for adding this. I've been out of the MacPorts game for years. Is someone else there maintaining those? Should we try to do something to ensure that latest versions are pushed to MacPorts too?

**Comment by skymoo** [comment]
@technoweenie I'm a MacPorts developer and just updated to the 1.2.0 release before filing this merge request. I'm subscribed to the git-lfs release RSS feed so I can keep an eye on releases and update as necessary.

We've recently started using git-lfs at work and it's in my best interest to make sure this is easy to install on Macs and as we use MacPorts extensively, making sure git-lfs is up-to-date in MacPorts is important to me. Whilst I'm not the official MacPorts maintainer for git-lfs it is what we call an Open Maintainer port so the maintainer has no objections to other developers updating it.

I am planning on making sure this is up-to-date in MacPorts going forward.

**Comment by technoweenie** [comment]
@skymoo Oh nice, thanks for elaborating. I've added a call-out on `git-lfs.github.com` as well.

**Comment by technoweenie** [comment]
Oh yeah, let us know if there's something the project could do to make things easier for you. You're welcome to open other issues or say hi in https://gitter.im/github/git-lfs/installation.

**Pull request merged**
