### PR TITLE
Fix pre-push hook with multiple branches

### LINKED ISSUE #632: Pre-push hook doesn't cope with pushing multiple branches at once
If you call `git push` with multiple branches, the pre-push hook only pushes objects for the first branch.
Example:
```
git push origin branch1 branch2 branch3 branch4
```
...will only push objects referenced in branch1.

### PR DESCRIPTION
**Pull request by sinbad**
Fixes #632

### CODE REVIEW

**Comment by technoweenie** [comment]
This looks great, but that's a lot of nesting. I'd have broken it up into smaller functions, but I don't think it's necessary here.

**Comment by sinbad** [comment]
It was only 1 extra level so I didn't really think about it, but I guess the 'for' is quite long now. I'll separate it and also rebase so I get the transfer queue fix.

**Comment by sinbad** [comment]
Dammit, bitten by the init random fail after rebase Xo It's fine, honest ;)

**Comment by ttaylorr** [comment]
Nice :+1:

**Comment by sinbad** [comment]
Lights are green :)

**Pull request merged**
